/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef flume_CONSTANTS_H
#define flume_CONSTANTS_H

#include "flume_types.h"

namespace flume_eio {

class flumeConstants {
 public:
  flumeConstants();

};

extern const flumeConstants g_flume_constants;

} // namespace

#endif
