/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef flume_eio_CONSTANTS_H
#define flume_eio_CONSTANTS_H

#include "flume_eio_types.h"

namespace flume_eio {

class flume_eioConstants {
 public:
  flume_eioConstants();

};

extern const flume_eioConstants g_flume_eio_constants;

} // namespace

#endif
