/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "flume_eio_constants.h"

namespace flume_eio {

const flume_eioConstants g_flume_eio_constants;

flume_eioConstants::flume_eioConstants() {
}

} // namespace

